---
- hosts: base
  become: yes
  tasks:
    - name: Add ictsc user
      user:
        name: ictsc
        password: "{{ lookup('env','ICTSC_PASSWORD') | password_hash('sha512') }}"
        groups: sudo
        #        ansible_distribution == 'Ubuntu'

    - name: Add write protect to /home/ictsc/.bash_history
      file:
        src: /dev/null
        dest: /home/ictsc/.bash_history
        state: link
        force: yes

    - name: Add write protect to /root/.bash_history
      file:
        src: /dev/null
        dest: /root/.bash_history
        state: link
        force: yes

    - name: Add admin user
      user:
        name: admin
        password: "!"
        groups: sudo

    - name: Add ictsc motd
      copy:
        src: ./motd
        dest: /etc/motd
        owner: root
        group: root

    - name: disable fail2ban
      systemd:
          name: fail2ban
          enabled: no

    - name: Set ictsc memeber's public key as authorized key
      authorized_key:
        user: ictsc
        key: "{{ item }}"
      with_file: keys
