---
- hosts: 127.0.0.1
  tasks:
    - name: Add ictsc user
      user:
        name: ictsc
        password: lookup("ICTSC_PASSWORD")
        groups: wheel

    - name: Add write protect to ~/.bash_history
      file:
        src: /home/ictsc/.bash_history
        dest: /dev/null
        state: link

    - name: Add write protect to ~/.bash_history
      file:
        src: /root/.bash_history
        dest: /dev/null
        state: link

    - name: Add admin user
      user:
        name: admin
        password: "!"
        groups: wheel

    - name: Add ictsc motd
      copy:
        src: ./motd
        dest: /etc/motd
        owner: root
        group: root

    - name: disable fail2ban
      systemd:
          name: fail2ban
          enabled: no

    - name: Set ictsc memeber's public key as authorized key
      authorized_key:
        user: ictsc

    - debug:
        msg: "{{ item }}"
      with_file: keys
