---
- hosts: test
  tasks:
    - name: Add ictsc user
      user:
        name: ictsc
        password: "{{ICTSC_PASSWORD}}"

    - name: Add write protect to ~/.bash_history
      file:
        src: /home/ictsc/.bash_history
        dest: /dev/null
        state: link

    - name: Add admin user
      user:
        name: admin
        password: "{{ADMIN_PASSWORD}}"

    - name: Add ictsc motd
      copy:
        src: ./motd
        dest: /etc/motd
        owner: root
        group: root

    - name: disable fail2ban
      systemd:
          name: fail2ban
          enabled: no
